name: "CI workflow"
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    container: "node:20-alpine" 
  steps:
    - uses: actions/checkout@v6
    - name: Install npm package
      run: npm install
    - name: lint codespace to ensure met standard style
      run: npm run lint
    - name: testing codebase
      run: npm test

    

